name: ptgms-utils
version: '${version}'
main: space.ptgms.util.Main
api-version: '1.20'

commands:
  wild:
    description: Teleport to a random location
    usage: /<command>
    aliases: [wilderness, tpwild, tpwilderness]
    permission: ptgmsUtils.wild
    permission-message: You don't have permission to use this command
  kickme:
    description: Kick yourself
    usage: /<command>
    aliases: [kickmyself]
  8ball:
    description: Ask the magic 8ball a question
    usage: /<command> <question>
    aliases: [8b, 8ball, ask8ball]
  calculator:
    description: Calculate your compatibility with someone
    usage: /<command> <name>
    aliases: [calc, compatibility, comp]
  spawnlimit:
    description: Set an Area new players can't leave without permission
    usage: /<command> <get/set> [radius]
    permission: ptgmsUtils.spawnlimit.set